taikoxyz/simple-taiko-node

- docker-compose.yml
Use `snaefellsjokull` tags for `taiko-geth` and `taiko-client` images, which will be maintained separately from the `latest` / `main` tags.
> chore(image): use `snaefellsjokull` tags

- script/start-prover-relayer.sh
The `zkevm-chain-prover-rpcd port` should respect environment variables like the rest of the script
>  Make Hard-coded prover's port dynamic

- .env.sample
On the line defining L2_THROWAWAY_BLOCK_BUILDER_PRIVATE_KEY there was a space at the end, then a comment. This was causing the following error:
"invalid throwaway blocks builder private key: invalid hex character ' ' in private key"
> fix(env): fix sample env file formatting

- script/start-prover-relayer.sh
The original script was using public ports instead of internal docker ports. However, the `l2_execution_engine` relies on the internal docker IP of `simple-taiko-node-l2_execution_engine`, so it should be using internal docker ports as well. 
Originally, if you change the default ports `PORT_L2_EXECTION_ENGINE_HTTP` and `PORT_L2_EXECTION_ENGINE_WS` in `.env` file, the prover relayer could not connect to the execution engine as it connects to the ports in `.env` file. However, it should connect to 8545 and 8546 to work properly.
> fix (script): use docker internal port

- script/l3/start-prover-relayer.sh
The value ${PORT_ZKEVM_CHAIN_PROVER_RPCD} set in .env.l3 should be used for the host.
> Use variable assignment for relayer port

- script/l3/start-zkevm-chain-rpcd.sh
Using :9000 works only if the .env.l3 variable is set to 9000.
> fix(eldfell): Use env variable for port assignment in zkevm rpcd script

- .env.sample.l3
I think L2 account is required for L3 prover.
> docs: update comments on .env.sample.l3

- script/l2/start-prover-relayer.sh
The curly brace is incorrect. As a result, the relayer does not work - simple-taiko-node-taiko_client_prover_relayer-1 exited with code 1.  This fix fixes the bug.
> fix(grimsvotn): fix `start-prover-relayer.sh` script

- script/l3/start-prover-relayer.sh
When using `--proveUnassignedBlocks false`, golang cli will parse the flag value as `true`, we need to use `--proveUnassignedBlocks=false`
> fix(eldfell): fix `--proveUnassignedBlocks` flag setting

- .env.sample.l3
change default PROVE_UNASSIGNED_BLOCKS true to false. 
If set to true, it will try to process unproved blocks in order, so completion will not be done unless the machine is strong. 
Set to false to change the default setting to process the block to which you are assigned.
> fix(prover): Update .env.sample.l3 change PROVE_UNASSIGNED_BLOCKS default value

- script/l3/start-prover-relayer.sh
we only need to set flag if its true, otherwise, do not need to set unassinged flags, can default to false
> fix(prover): flag can be invalid

- .gitignore
- script/util/update-env.sh
util command to update .env file from sample. updates any default values we set, but retains user defined values. a default value is one defined in the sample, a user defined value is one that is blank in the sample. makes sure to update all comments and stuff.
v1 of this feature to improve quality of life. in the future i think we could perhaps distribute a binary (from rust) for a command called "stn" (simple-taiko-node), which we can have the user install from a github release, via a curl command. we'd have the rust code here, compile and release the target binaries on github action, and have the user install it over curl like `curl github.com/releases/blah | bash`. see: https://raw.githubusercontent.com/foundry-rs/foundry/master/foundryup/install.
then we can alias those docker …
> feat: add update-env.sh util script

- .env.sample.l3
- script/l3/start-prover-relayer.sh
pr relies on https://github.com/taikoxyz/taiko-client/pull/362
this will let people skip every N blocks, which should help with our unverified blocks backlog, since many peopel are competing for the same block, even with 60,000 unverified blocks.
setting PROOF_SKIP_SIZE=randomNumber will let the user prove a block with less chance of collision.
> feat(prover): proof skip size for l3

- .env.sample
- script/start-prover-relayer.sh
relies on https://github.com/taikoxyz/taiko-client/pull/407 being cherry picked into jolnir.
community wanted to prove unassigned blocks again, so i re-added the flag.
> fix(prover): prover needs taikotoken address, and re-add prove unassigned blocks

- script/start-proposer.sh
Encountered an issue where the script would hang indefinitely without any feedback due to the ENABLE_PROPOSER being set to false. This enhancement introduces an explicit echo notification to inform the user that the proposer is disabled before the script enters an infinite sleep. This provides clearer context during execution.
> feat(node): Echo Notification for Disabled Proposer Prior to Infinite Sleep

- .env.sample
Changed the IP address format in the .env.sample file from 'http:/192.168.1.15:8545' to 'http://192.168.1.15:8545'. This corrects an issue that could lead to connection problems for new users attempting to connect to the archive node using these endpoint examples
> fix: correct IP format in .env.sample endpoints

- .env.sample
Previously, Infura or Alchemy were recomended for their free Sepolia endpoint but they don't offer a Holesky endpoint. BlockPi does, so I propose referring users to that service instead for Alpha 6
> fix: Update L1 Provider tip

- script/start-prover-relayer.sh
- script/start-zkevm-chain-rpcd.sh
This adds a `PROVER IS DISABLED` echo in `start-prover-relayer.sh` and `start-zkevm-chain-rpcd.sh`, when the prover is disabled. This is useful when reviewing the log, and spotting potential `.env` issues in enabling the prover. A similar message already exists for `start-proposer.sh`.
Example usage for spotting it in log:
```
root@host:~/simple-taiko-node# docker compose logs -f taiko_client_prover_relayer
simple-taiko-node-taiko_client_prover_relayer-1  | PROVER IS DISABLED
root@host:~/simple-taiko-node# docker compose logs -f zkevm_chain_prover_rpcd
simple-taiko-node-zkevm_chain_prover_rpcd-1  | PROVER IS DISABLED
```
> feat(prover): add `PROVER IS DISABLED` log

- docker-compose.yml
Removes the obsolete docker-compose.yml version warning
fixes https://github.com/taikoxyz/simple-taiko-node/issues/210
> fix: remove obsolete docker-compose.yml version

- .env.sample
Issues Encountered:
I noticed an inconsistency in the description and the input format for TOKEN_ALLOWANCE= and MIN_TKO_BALANCE=. Specifically, the format for TOKEN_ALLOWANCE= led to a significant error where I unintentionally approved 251e+38, resulting in a loss of 2000 TTKOh within just 10 minutes.
These revisions aim to clarify that the values should be entered in the smallest unit and provide explicit examples directly in the comments. I believe these changes will make the configuration settings more intuitive and prevent costly errors.
Thank you for considering these modifications.
> feat: Updated .env.sample to clarify token amounts

- .env.sample
Added description for L1_BEACON_HTTP, as often errors came up for users using a third party host where the API key is part of the URL.
> docs: Update .env.sample

- docker-compose.yml
To ignore the `0` gas price anchor transactions when doing the gas price suggestion.
> feat(hekla): introduce `--gpo.ignoreprice` flag

- docker/grafana/custom/l2/provisioning/dashboards/l2-execution-engine-overview-dashboard.json
This ensures that metrics like `latest header`, `latest receipt`, and `latest block` display the accurate last state values instead of averages from the time series.
fixes #246
> fix(grafana): Set 'Instant' as default query type for instant metrics

- docker-compose.yml
With the current configuration, geth broadcasts the wrong port and can only connect to bootnodes from the env file.
> fix: update docker-compose.yml for better p2p configuration

- docker-compose.yml
Added a default value for GETH_ADDITIONAL_ARGS to remove the annoying warning `The "GETH_ADDITIONAL_ARGS" variable is not set.`
> fix: add default value for GETH_ADDITIONAL_ARGS

- script/start-prover-relayer.sh
[prover](https://github.com/taikoxyz/taiko-mono/blob/486c126902302c724a2b45d769bbbfe85b6ed0be/packages/taiko-client/cmd/flags/prover.go#L214) no longer uses l1beacon (?)
> fix: remove unused flag

- .env.sample
- .env.sample.hekla
I have added in the .env.sample files the descriptions in both mainnet and testnet, so they can use theirs L1 node as beacon RPC.
> chore(main): Updating both .env.sample explaining how to use REST port.

- .env.sample.hekla
> chore(env): update `.env.sample.hekla`

- .env.sample
- .env.sample.hekla
- docker-compose-hekla.yml
- script/start-proposer-hekla.sh
- script/start-proposer.sh
- script/start-prover-relayer-hekla.sh
- script/start-prover-relayer.sh
Will release a fork version, I'm working on the release note, could you help me try this version on Hekla? @RogerLamTd
> chore(prover,proposer,driver): upgrade client version to `0.43.0` on Hekla

- .env.sample
- .env.sample.hekla
- script/start-proposer-hekla.sh
- script/start-proposer.sh
- script/start-prover-relayer-hekla.sh
- script/start-prover-relayer.sh
> chore(prover,proposer): script and env improvements
